name: ChallengeMe
version: @version@
main: me.jishuna.challengeme.ChallengeMe
authors: [Jishuna]
api-version: 1.16
softdepend: [ProtocolLib]

commands:
  challenges:
    description: 'Open the challenge GUI'
  challengeme:
    description: 'Base plugin command'