name: ChallengeMe
version: @version@
main: me.jishuna.challengeme.ChallengeMe
authors: [Jishuna]
api-version: 1.16
depend: [ProtocolLib]

commands:
  challenges:
    description: 'Open the challenge GUI'